### ISSUE TITLE
Python.ipynb Terminology and Spacing

### ISSUE THREAD

**Issue by mbozada** [cse-devteam/Programmers-Guide-to-the-Galaxy#11]
@CodingPenguin1 

Love the python guide! I think it's a great, quick overview of the language. However, I'm already 75% comfortable with writing in python, so I don't know how a true beginner will feel about it.

A couple of things:
Python is strongly, dynamically typed. I totally get what you mean when you say python is loosely-typed, but it may be better to use terminology people will encounter later on, dynamic vs. static, strong vs. weak.
![typing](https://user-images.githubusercontent.com/52613673/113767224-6d971c00-96ec-11eb-86a2-cea0dd789085.png)

I think one of your sections of lists could be split up into more cells:
![too_long](https://user-images.githubusercontent.com/52613673/113767482-bcdd4c80-96ec-11eb-8416-ca280f8898ab.png)

Also, you cover iterating with negative values in iterables, but repeat it again in lists. I think it is good to reiterate (ha), but the wording could be changed to help flow.

Finally, you mention that you can use ':' to get a subset of an iterable. I think it may be good to mention that peeps refer to them as slices, even though they really are just subsets.

I think that's everything I found on my first look. Hope this helps!

**Comment by CodingPenguin1** [comment]
Agreed. Resolved with #12
