### ISSUE TITLE
Git guide should cover Issues and Project Boards

### ISSUE THREAD

**Issue by cousinvinnys** [cse-devteam/Programmers-Guide-to-the-Galaxy#27]
## [Issues](https://guides.github.com/features/issues/)

Use issues to track ideas, enhancements, tasks, or bugs for work on GitHub.

## Project Boards

Project boards on GitHub help you organize and prioritize your work. You can create project boards for specific feature work, comprehensive roadmaps, or even release checklists. With project boards, you have the flexibility to create customized workflows that suit your needs.

**Comment by CodingPenguin1** [comment]
Duplicate of #30
